### ISSUE TITLE
نقد به این پروژه

### ISSUE THREAD

**Issue by NabiKAZ** [erfanmola/NoJQuery#2]
<div dir=rtl>

میخواستم یه نقد به این پروژه وارد کنم.
یکی از بزرگترین ویژگی های مثبت جی کوئری یکسان سازی دستورات و اطمینان از اجرای کدها در انواع مرورگرهاست، البته این قضیه قدیم خیلی حاد تر بود که باید سه چهار تا if میزدید اگر فلان مرورگر بود فلان جور رفتار کن و الان یک مقدار بهتر شده. مثلاً کدی که برای آژاکس نوشتید اصلاً در IE قدیمیتر قابل اجرا نیست و خب چون هر مرورگر ساز خودش رو میزنه درمورد نحوه اجرای کدهای js، فریم ورک ها اختراع شدند تا اطمینان بدن سایت ما در همه مرورگرها یکسان کار میکنه، به همین خاطر این موضوع مهمیه و نمیشه به خاطر مثلاً حجم زیاد(که چندان هم زیاد نیست) به آسانی اونها رو نادیده گرفت.
در ضمن اشاره شما به حجم زیاد هم نقد بهش وارده چراکه اگر از CDN های معتبر استفاده بشه (یا حتی نشه اما از درخواست دوم به بعد برای یک سایت) با توجه به اینکه درخواست ها روی بروزر کش میشن، حتی شاید همون 2کیلوبایت در وضعیت پلین حجیم تر از 300 کیلوبایت(که بعد از کش شدن صفر کیلوبایته) در این مثاله.

پ.ن: راستی جسارتاً برای هر مقاله لزومی نداره یک سایت مستقل یا یک پروژه گیت هاب بیارید بالا ;-) میتونید همه رو توی یک وبلاگ یا ویرگول یکجا بنویسید :-) (البته این فقط یک نظر شخصی بود)

**Comment by erfanmola** [comment]
سلام وقت‌بخیر، خیلی ممنونم بابت نقد و وقتی که گذاشتید
بله درسته در این مورد حق با شماست، توی پروژه هایی در مقیاس بالا تر، حفظ سازگاری و نوشتن پُلی‌فیل برای تمامی مرورگرها، کار رو سخت‌تر می‌کنه و آدم یه جایی به خودش میاد و میبینه که بیشتر از کل حجم کتابخونه جی‌کوئری، صرفا پلی‌فیل نوشته

ولی توی اسکیل های کوچیک مثل یک پروژه تک صفحه‌ای یا حتی یه پروژه ساده هلو ورلد، این یه عادت بد شده که همه میان جی‌کوئری لود می‌کنند

یه موردی که وجود داره اینه که متاسفانه ما توی ایران زندگی می‌کنیم و درسته که اینترنت در سطح شهرها اوکی هست، ولی روستا های زیادی وجود دارند که هنوز با نت نسل دوم موبایل وارد وبسایت‌ها میشن، وقتی آدم خودش رو جای اون‌ها میزاره واقعا می‌فهمه که ۱۰۰ کیلوبایت هم در جای خودش ۱۰۰ کیلوبایته ! بهرحال خودمون هم مدت زیادی رو با کندی اینترنت و دایال‌آپ و اینترنت نسل دو تجربه کردیم و آدم می‌تونه درک کنه که چقدر می‌تونه بد باشه تجربه لود اول وبسایت (که منطقا تاثیر زیادی رو نرخ بازگشت های بعدی کاربر داره)

درمورد مورد آخری هم که ذکر کردید، بله درسته روش اصولی‌اش این هست که در یک بستری به‌صورت منسجم ارائه بشه کارها، ولی خب از اونجایی که دامنه آی‌آر ارزون هست و سنگ مفته و گنجشک مفت، تهیه یه دامنه و بالا آوردن سایت روی اون می‌تونه باعث ماندگاری‌اش توی ذهن مخاطب بشه
چون پروژه‌ای که بر بستر یک پلتفرم محتوایی ارائه بشه توی ذهن مخاطب به مدت محدودی میمونه، ولی دامنه مجزا نقش یک سایت مجزا رو ایفا می‌کنه و ماندگاری بیشتری توی ذهن مخاطب داره

باز هم خیلی ممنونم از وقتی گذاشتید و نظری که دادید، کاملا صحیح هست فرمایش‌تون
